export const ENV_KEYS = {
  POSTGRES_URL:'POSTGRES_URL',
  PORT: 'PORT',

  BCRYPT_SALT: 'BCRYPT_SALT',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',

  JWT_ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_EXPIRATION: 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_SECRET: 'JWT_SECRET',
  AUTH_CODE_EXPIRATION: 'AUTH_CODE_EXPIRATION',

  RESEND_API_KEY: 'RESEND_API_KEY',
  NCANODE_URL: 'NCANODE_URL'
};
