export const ENV_KEYS = {
  POSTGRES_URL: 'POSTGRES_URL',
  PORT: 'PORT',

  BCRYPT_SALT: 'BCRYPT_SALT',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',

  JWT_ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_EXPIRATION: 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_SECRET: 'JWT_SECRET',
  AUTH_CODE_EXPIRATION: 'AUTH_CODE_EXPIRATION',

  MAIL_HOST: 'MAIL_HOST',
  MAIL_PORT: 'MAIL_PORT',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',
  MAIL_FROM: 'MAIL_FROM',

  NCANODE_URL: 'NCANODE_URL',
  TEST_SECRET_KEY: 'TEST_SECRET_KEY',
};
