export enum SurveyType {
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  HEALTHCARE = 'HEALTHCARE',
  DIGITALIZATION = 'DIGITALIZATION',
  ECONOMY = 'ECONOMY',
  ECOLOGY = 'ECOLOGY',
  EDUCATION = 'EDUCATION',
}
